/*
 * Created on 2022-07-29 ( 20:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "Adminmaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="AdminMaster", schema="dbo", catalog="Struts2app" )
public class Adminmaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="ademailid", nullable=false, length=50)
    private String     ademailid ;

    public Adminmaster(String ademailid, String adpass, String adname, BigDecimal admobile) {
		super();
		this.ademailid = ademailid;
		this.adpass = adpass;
		this.adname = adname;
		this.admobile = admobile;
	}

	//--- ENTITY DATA FIELDS 
    @Column(name="adpass", nullable=false, length=20)
    private String     adpass ;

    @Column(name="adname", nullable=false, length=20)
    private String     adname ;

    @Column(name="admobile", nullable=false)
    private BigDecimal admobile ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Adminmaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setAdemailid( String ademailid ) {
        this.ademailid = ademailid ;
    }
    public String getAdemailid() {
        return this.ademailid;
    }

    public void setAdpass( String adpass ) {
        this.adpass = adpass ;
    }
    public String getAdpass() {
        return this.adpass;
    }

    public void setAdname( String adname ) {
        this.adname = adname ;
    }
    public String getAdname() {
        return this.adname;
    }

    public void setAdmobile( BigDecimal admobile ) {
        this.admobile = admobile ;
    }
    public BigDecimal getAdmobile() {
        return this.admobile;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(ademailid);
        sb.append("|");
        sb.append(adpass);
        sb.append("|");
        sb.append(adname);
        sb.append("|");
        sb.append(admobile);
        return sb.toString(); 
    } 

}
