/*
 * Created on 2022-07-29 ( 20:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Appointmentmaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="AppointmentMaster", schema="dbo", catalog="Struts2app" )
public class Appointmentmaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="appid", nullable=false)
    private BigDecimal appid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="packid", nullable=false)
    private BigDecimal packid ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="apptime", nullable=false)
    private Date       apptime ;

    @Column(name="useremail", nullable=false, length=2147483647)
    private String     useremail ;

    @Column(name="appstatus", nullable=false, length=15)
    private String     appstatus ;

    @Column(name="appadress", nullable=false, length=2147483647)
    private String     appadress ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Appointmentmaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setAppid( BigDecimal appid ) {
        this.appid = appid ;
    }
    public BigDecimal getAppid() {
        return this.appid;
    }

    public void setPackid( BigDecimal packid ) {
        this.packid = packid ;
    }
    public BigDecimal getPackid() {
        return this.packid;
    }

    public void setApptime( Date apptime ) {
        this.apptime = apptime ;
    }
    public Date getApptime() {
        return this.apptime;
    }

    public void setUseremail( String useremail ) {
        this.useremail = useremail ;
    }
    public String getUseremail() {
        return this.useremail;
    }

    public void setAppstatus( String appstatus ) {
        this.appstatus = appstatus ;
    }
    public String getAppstatus() {
        return this.appstatus;
    }

    public void setAppadress( String appadress ) {
        this.appadress = appadress ;
    }
    public String getAppadress() {
        return this.appadress;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(appid);
        sb.append("|");
        sb.append(packid);
        sb.append("|");
        sb.append(apptime);
        sb.append("|");
        sb.append(useremail);
        sb.append("|");
        sb.append(appstatus);
        sb.append("|");
        sb.append(appadress);
        return sb.toString(); 
    } 

}
