/*
 * Created on 2022-07-29 ( 20:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;


import java.io.Serializable;
import java.math.BigDecimal;

public class Cartmaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private String     userid ;

    private BigDecimal prodid ;

    private BigDecimal quantity ;



    public Cartmaster() {
		super();
    }
    
    public void setUserid( String userid ) {
        this.userid = userid ;
    }
    public String getUserid() {
        return this.userid;
    }

    public void setProdid( BigDecimal prodid ) {
        this.prodid = prodid ;
    }
    public BigDecimal getProdid() {
        return this.prodid;
    }

    public void setQuantity( BigDecimal quantity ) {
        this.quantity = quantity ;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(userid);
        sb.append("|");
        sb.append(prodid);
        sb.append("|");
        sb.append(quantity);
        return sb.toString(); 
    } 

}
