/*
 * Created on 2022-07-29 ( 20:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Ordermaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="OrderMaster", schema="dbo", catalog="Struts2app" )
public class Ordermaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="OrderID", nullable=false)
    private BigDecimal orderid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="useremail", nullable=false, length=2147483647)
    private String     useremail ;

    @Column(name="prodid", nullable=false)
    private BigDecimal prodid ;

    @Temporal(TemporalType.DATE)
    @Column(name="orderdate", nullable=false)
    private Date       orderdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="orderdeliverydate", nullable=false)
    private Date       orderdeliverydate ;

    @Column(name="deliverycharge", nullable=false)
    private BigDecimal deliverycharge ;

    @Column(name="odbillamount", nullable=false)
    private BigDecimal odbillamount ;

    @Column(name="payementmode", nullable=false, length=2147483647)
    private String     payementmode ;

    @Column(name="status", nullable=false, length=2147483647)
    private String     status ;

    @Column(name="paidornot", nullable=false, length=2147483647)
    private String     paidornot ;

    @Column(name="address", nullable=false, length=2147483647)
    private String     address ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Ordermaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrderid( BigDecimal orderid ) {
        this.orderid = orderid ;
    }
    public BigDecimal getOrderid() {
        return this.orderid;
    }

    public void setUseremail( String useremail ) {
        this.useremail = useremail ;
    }
    public String getUseremail() {
        return this.useremail;
    }

    public void setProdid( BigDecimal prodid ) {
        this.prodid = prodid ;
    }
    public BigDecimal getProdid() {
        return this.prodid;
    }

    public void setOrderdate( Date orderdate ) {
        this.orderdate = orderdate ;
    }
    public Date getOrderdate() {
        return this.orderdate;
    }

    public void setOrderdeliverydate( Date orderdeliverydate ) {
        this.orderdeliverydate = orderdeliverydate ;
    }
    public Date getOrderdeliverydate() {
        return this.orderdeliverydate;
    }

    public void setDeliverycharge( BigDecimal deliverycharge ) {
        this.deliverycharge = deliverycharge ;
    }
    public BigDecimal getDeliverycharge() {
        return this.deliverycharge;
    }

    public void setOdbillamount( BigDecimal odbillamount ) {
        this.odbillamount = odbillamount ;
    }
    public BigDecimal getOdbillamount() {
        return this.odbillamount;
    }

    public void setPayementmode( String payementmode ) {
        this.payementmode = payementmode ;
    }
    public String getPayementmode() {
        return this.payementmode;
    }

    public void setStatus( String status ) {
        this.status = status ;
    }
    public String getStatus() {
        return this.status;
    }

    public void setPaidornot( String paidornot ) {
        this.paidornot = paidornot ;
    }
    public String getPaidornot() {
        return this.paidornot;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(orderid);
        sb.append("|");
        sb.append(useremail);
        sb.append("|");
        sb.append(prodid);
        sb.append("|");
        sb.append(orderdate);
        sb.append("|");
        sb.append(orderdeliverydate);
        sb.append("|");
        sb.append(deliverycharge);
        sb.append("|");
        sb.append(odbillamount);
        sb.append("|");
        sb.append(payementmode);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(paidornot);
        sb.append("|");
        sb.append(address);
        return sb.toString(); 
    } 

}
