/*
 * Created on 2022-07-29 ( 20:25:35 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "Packagemaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="PackageMaster", schema="dbo", catalog="Struts2app" )
public class Packagemaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="packid", nullable=false)
    private BigDecimal packid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="packname", nullable=false, length=2147483647)
    private String     packname ;

    @Column(name="packdesc", nullable=false, length=2147483647)
    private String     packdesc ;

    @Column(name="price", nullable=false, length=2147483647)
    private String     price ;

    @Column(name="avgtime", nullable=false)
    private BigDecimal avgtime ;

    @Column(name="packimg", nullable=false, length=2147483647)
    private String     packimg ;

    @Column(name="beautician", nullable=false, length=2147483647)
    private String     beautician ;

    @Column(name="sellerid", nullable=false)
    private BigDecimal sellerid ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Packagemaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setPackid( BigDecimal packid ) {
        this.packid = packid ;
    }
    public BigDecimal getPackid() {
        return this.packid;
    }

    public void setPackname( String packname ) {
        this.packname = packname ;
    }
    public String getPackname() {
        return this.packname;
    }

    public void setPackdesc( String packdesc ) {
        this.packdesc = packdesc ;
    }
    public String getPackdesc() {
        return this.packdesc;
    }

    public void setPrice( String price ) {
        this.price = price ;
    }
    public String getPrice() {
        return this.price;
    }

    public void setAvgtime( BigDecimal avgtime ) {
        this.avgtime = avgtime ;
    }
    public BigDecimal getAvgtime() {
        return this.avgtime;
    }

    public void setPackimg( String packimg ) {
        this.packimg = packimg ;
    }
    public String getPackimg() {
        return this.packimg;
    }

    public void setBeautician( String beautician ) {
        this.beautician = beautician ;
    }
    public String getBeautician() {
        return this.beautician;
    }

    public void setSellerid( BigDecimal sellerid ) {
        this.sellerid = sellerid ;
    }
    public BigDecimal getSellerid() {
        return this.sellerid;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(packid);
        sb.append("|");
        sb.append(packname);
        sb.append("|");
        sb.append(packdesc);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(avgtime);
        sb.append("|");
        sb.append(packimg);
        sb.append("|");
        sb.append(beautician);
        sb.append("|");
        sb.append(sellerid);
        return sb.toString(); 
    } 

}
