/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Paymentmaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="PaymentMaster", schema="dbo", catalog="Struts2app" )
public class Paymentmaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="payid", nullable=false)
    private BigDecimal payid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="orderid", nullable=false)
    private BigDecimal orderid ;

    @Column(name="useremail", nullable=false, length=50)
    private String     useremail ;

    @Temporal(TemporalType.DATE)
    @Column(name="paydate", nullable=false)
    private Date       paydate ;

    @Column(name="payamount", nullable=false)
    private BigDecimal payamount ;

    @Column(name="paymode", nullable=false, length=2147483647)
    private String     paymode ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Paymentmaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setPayid( BigDecimal payid ) {
        this.payid = payid ;
    }
    public BigDecimal getPayid() {
        return this.payid;
    }

    public void setOrderid( BigDecimal orderid ) {
        this.orderid = orderid ;
    }
    public BigDecimal getOrderid() {
        return this.orderid;
    }

    public void setUseremail( String useremail ) {
        this.useremail = useremail ;
    }
    public String getUseremail() {
        return this.useremail;
    }

    public void setPaydate( Date paydate ) {
        this.paydate = paydate ;
    }
    public Date getPaydate() {
        return this.paydate;
    }

    public void setPayamount( BigDecimal payamount ) {
        this.payamount = payamount ;
    }
    public BigDecimal getPayamount() {
        return this.payamount;
    }

    public void setPaymode( String paymode ) {
        this.paymode = paymode ;
    }
    public String getPaymode() {
        return this.paymode;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(payid);
        sb.append("|");
        sb.append(orderid);
        sb.append("|");
        sb.append(useremail);
        sb.append("|");
        sb.append(paydate);
        sb.append("|");
        sb.append(payamount);
        sb.append("|");
        sb.append(paymode);
        return sb.toString(); 
    } 

}
