/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;

public class Productdescript implements Serializable {

    public static final long serialVersionUID = 1L;

    public String prodid ;

    public String     productname ;

	public String     prodimage ;

    public String     procolor ;

    public String sellerid ;

    public String price ;

    public Productdescript(String prodid, String productname, String prodimage, String procolor, String sellerid,
			String price, String mrpprice, String avgrating, String noofratings, String noofreviews,
			String warrantyperiod, String returnperiod, String codpolicy, String quantity, String tags,
			String discount) {
		super();
		this.prodid = prodid;
		this.productname = productname;
		this.prodimage = prodimage;
		this.procolor = procolor;
		this.sellerid = sellerid;
		this.price = price;
		this.mrpprice = mrpprice;
		this.avgrating = avgrating;
		this.noofratings = noofratings;
		this.noofreviews = noofreviews;
		this.warrantyperiod = warrantyperiod;
		this.returnperiod = returnperiod;
		this.codpolicy = codpolicy;
		this.quantity = quantity;
		this.tags = tags;
		this.discount = discount;
	}

	public String mrpprice ;

    public String avgrating ;

    public String noofratings ;

    public String noofreviews ;

    public String warrantyperiod ;

    public String returnperiod ;

    public String     codpolicy ;

    public String quantity ;

    public String     tags ;

    public String discount ;


    public Productdescript() {
		super();
    }
  
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(prodid);
        sb.append("|");
        sb.append(productname);
        sb.append("|");
        sb.append(prodimage);
        sb.append("|");
        sb.append(procolor);
        sb.append("|");
        sb.append(sellerid);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(mrpprice);
        sb.append("|");
        sb.append(avgrating);
        sb.append("|");
        sb.append(noofratings);
        sb.append("|");
        sb.append(noofreviews);
        sb.append("|");
        sb.append(warrantyperiod);
        sb.append("|");
        sb.append(returnperiod);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(tags);
        sb.append("|");
        sb.append(discount);
        return sb.toString(); 
    } 

}
