/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Rentmaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="RentMaster", schema="dbo", catalog="Struts2app" )
public class Rentmaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="appid", nullable=false)
    private BigDecimal appid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="prodid", nullable=false)
    private BigDecimal prodid ;

    @Column(name="securitydeposit", nullable=false)
    private BigDecimal securitydeposit ;

    @Column(name="charge")
    private BigDecimal charge ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starttime", nullable=false)
    private Date       starttime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="endtime", nullable=false)
    private Date       endtime ;

    @Column(name="useremail", nullable=false, length=2147483647)
    private String     useremail ;

    @Column(name="rentstatus", nullable=false, length=15)
    private String     rentstatus ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Rentmaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setAppid( BigDecimal appid ) {
        this.appid = appid ;
    }
    public BigDecimal getAppid() {
        return this.appid;
    }

    public void setProdid( BigDecimal prodid ) {
        this.prodid = prodid ;
    }
    public BigDecimal getProdid() {
        return this.prodid;
    }

    public void setSecuritydeposit( BigDecimal securitydeposit ) {
        this.securitydeposit = securitydeposit ;
    }
    public BigDecimal getSecuritydeposit() {
        return this.securitydeposit;
    }

    public void setCharge( BigDecimal charge ) {
        this.charge = charge ;
    }
    public BigDecimal getCharge() {
        return this.charge;
    }

    public void setStarttime( Date starttime ) {
        this.starttime = starttime ;
    }
    public Date getStarttime() {
        return this.starttime;
    }

    public void setEndtime( Date endtime ) {
        this.endtime = endtime ;
    }
    public Date getEndtime() {
        return this.endtime;
    }

    public void setUseremail( String useremail ) {
        this.useremail = useremail ;
    }
    public String getUseremail() {
        return this.useremail;
    }

    public void setRentstatus( String rentstatus ) {
        this.rentstatus = rentstatus ;
    }
    public String getRentstatus() {
        return this.rentstatus;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(appid);
        sb.append("|");
        sb.append(prodid);
        sb.append("|");
        sb.append(securitydeposit);
        sb.append("|");
        sb.append(charge);
        sb.append("|");
        sb.append(starttime);
        sb.append("|");
        sb.append(endtime);
        sb.append("|");
        sb.append(useremail);
        sb.append("|");
        sb.append(rentstatus);
        return sb.toString(); 
    } 

}
