/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "Rentproductdescript"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="rentproductdescript", schema="dbo", catalog="Struts2app" )
public class Rentproductdescript implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ProdID", nullable=false)
    private BigDecimal prodid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Productname", nullable=false, length=2147483647)
    private String     productname ;

    @Column(name="prodimage", nullable=false, length=2147483647)
    private String     prodimage ;

    @Column(name="procolor", nullable=false, length=2147483647)
    private String     procolor ;

    @Column(name="sellerid", nullable=false)
    private BigDecimal sellerid ;

    @Column(name="price", nullable=false)
    private BigDecimal price ;

    @Column(name="mrpprice", nullable=false)
    private BigDecimal mrpprice ;

    @Column(name="quantity", nullable=false)
    private BigDecimal quantity ;

    @Column(name="tags", nullable=false, length=2147483647)
    private String     tags ;

    @Column(name="discount")
    private BigDecimal discount ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Rentproductdescript() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setProdid( BigDecimal prodid ) {
        this.prodid = prodid ;
    }
    public BigDecimal getProdid() {
        return this.prodid;
    }

    public void setProductname( String productname ) {
        this.productname = productname ;
    }
    public String getProductname() {
        return this.productname;
    }

    public void setProdimage( String prodimage ) {
        this.prodimage = prodimage ;
    }
    public String getProdimage() {
        return this.prodimage;
    }

    public void setProcolor( String procolor ) {
        this.procolor = procolor ;
    }
    public String getProcolor() {
        return this.procolor;
    }

    public void setSellerid( BigDecimal sellerid ) {
        this.sellerid = sellerid ;
    }
    public BigDecimal getSellerid() {
        return this.sellerid;
    }

    public void setPrice( BigDecimal price ) {
        this.price = price ;
    }
    public BigDecimal getPrice() {
        return this.price;
    }

    public void setMrpprice( BigDecimal mrpprice ) {
        this.mrpprice = mrpprice ;
    }
    public BigDecimal getMrpprice() {
        return this.mrpprice;
    }

    public void setQuantity( BigDecimal quantity ) {
        this.quantity = quantity ;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public void setTags( String tags ) {
        this.tags = tags ;
    }
    public String getTags() {
        return this.tags;
    }

    public void setDiscount( BigDecimal discount ) {
        this.discount = discount ;
    }
    public BigDecimal getDiscount() {
        return this.discount;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(prodid);
        sb.append("|");
        sb.append(productname);
        sb.append("|");
        sb.append(prodimage);
        sb.append("|");
        sb.append(procolor);
        sb.append("|");
        sb.append(sellerid);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(mrpprice);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(tags);
        sb.append("|");
        sb.append(discount);
        return sb.toString(); 
    } 

}
