/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "Reviewtable"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="ReviewTable", schema="dbo", catalog="Struts2app" )
public class Reviewtable implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ReviewID", nullable=false)
    private BigDecimal reviewid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="ProdID", nullable=false)
    private BigDecimal prodid ;

    @Column(name="RevMsg", length=2147483647)
    private String     revmsg ;

    @Column(name="RevStars")
    private BigDecimal revstars ;

    @Column(name="RevUsername", nullable=false, length=50)
    private String     revusername ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Reviewtable() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setReviewid( BigDecimal reviewid ) {
        this.reviewid = reviewid ;
    }
    public BigDecimal getReviewid() {
        return this.reviewid;
    }

    public void setProdid( BigDecimal prodid ) {
        this.prodid = prodid ;
    }
    public BigDecimal getProdid() {
        return this.prodid;
    }

    public void setRevmsg( String revmsg ) {
        this.revmsg = revmsg ;
    }
    public String getRevmsg() {
        return this.revmsg;
    }

    public void setRevstars( BigDecimal revstars ) {
        this.revstars = revstars ;
    }
    public BigDecimal getRevstars() {
        return this.revstars;
    }

    public void setRevusername( String revusername ) {
        this.revusername = revusername ;
    }
    public String getRevusername() {
        return this.revusername;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(reviewid);
        sb.append("|");
        sb.append(prodid);
        sb.append("|");
        sb.append(revmsg);
        sb.append("|");
        sb.append(revstars);
        sb.append("|");
        sb.append(revusername);
        return sb.toString(); 
    } 

}
