/*
 * Created on 2022-07-29 ( 20:25:36 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "Sellermaster"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="SellerMaster", schema="dbo", catalog="Struts2app" )
public class Sellermaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="sellerid", nullable=false)
    private BigDecimal sellerid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="saddress", nullable=false, length=2147483647)
    private String     saddress ;

    @Column(name="smobile", nullable=false)
    private BigDecimal smobile ;

    @Column(name="semail", nullable=false, length=2147483647)
    private String     semail ;

    @Column(name="spass", nullable=false, length=2147483647)
    private String     spass ;

    @Column(name="sfirmname", nullable=false, length=2147483647)
    private String     sfirmname ;

    @Column(name="sgstno", nullable=false, length=2147483647)
    private String     sgstno ;

    @Column(name="spanno", length=2147483647)
    private String     spanno ;

    @Column(name="approved", nullable=false, length=10)
    private String     approved ;

    @Column(name="scity", nullable=false, length=2147483647)
    private String     scity ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Sellermaster() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setSellerid( BigDecimal sellerid ) {
        this.sellerid = sellerid ;
    }
    public BigDecimal getSellerid() {
        return this.sellerid;
    }

    public void setSaddress( String saddress ) {
        this.saddress = saddress ;
    }
    public String getSaddress() {
        return this.saddress;
    }

    public void setSmobile( BigDecimal smobile ) {
        this.smobile = smobile ;
    }
    public BigDecimal getSmobile() {
        return this.smobile;
    }

    public void setSemail( String semail ) {
        this.semail = semail ;
    }
    public String getSemail() {
        return this.semail;
    }

    public void setSpass( String spass ) {
        this.spass = spass ;
    }
    public String getSpass() {
        return this.spass;
    }

    public void setSfirmname( String sfirmname ) {
        this.sfirmname = sfirmname ;
    }
    public String getSfirmname() {
        return this.sfirmname;
    }

    public void setSgstno( String sgstno ) {
        this.sgstno = sgstno ;
    }
    public String getSgstno() {
        return this.sgstno;
    }

    public void setSpanno( String spanno ) {
        this.spanno = spanno ;
    }
    public String getSpanno() {
        return this.spanno;
    }

    public void setApproved( String approved ) {
        this.approved = approved ;
    }
    public String getApproved() {
        return this.approved;
    }

    public void setScity( String scity ) {
        this.scity = scity ;
    }
    public String getScity() {
        return this.scity;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(sellerid);
        sb.append("|");
        sb.append(saddress);
        sb.append("|");
        sb.append(smobile);
        sb.append("|");
        sb.append(semail);
        sb.append("|");
        sb.append(spass);
        sb.append("|");
        sb.append(sfirmname);
        sb.append("|");
        sb.append(sgstno);
        sb.append("|");
        sb.append(spanno);
        sb.append("|");
        sb.append(approved);
        sb.append("|");
        sb.append(scity);
        return sb.toString(); 
    } 

}
